apiVersion: 1

deleteDatasources:
  - name: Influx
    orgId: 1

datasources:
  - name: Influx
    type: influxdb
    access: proxy
    orgId: 1
    url: http://127.0.0.1:8086
    database: telegraf
    user: telegraf
    password: telegraf
    isDefault: false
    editable: true
