version: "3.0"

services:
  influxdb:
    container_name: "influxdb"
    image: "influxdb:1.7"
    network_mode: "host"
    ports:
      - "8086:8086"
    volumes:
      - "${PWD}/influxdb:/var/lib/influxdb"
    environment:
      INFLUXDB_DB: "telegraf"
      INFLUXDB_ADMIN_USER: "telegraf"
      INFLUXDB_ADMIN_PASSWORD: "telegraf"
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      DS_INFLUXDB_TELEGRAF: "InfluxDB"
    restart: "always"

  grafana:
    container_name: "grafana"
    image: "grafana/grafana:7.5.7"
    network_mode: "host"
    ports:
      - "3000:3000"
    volumes:
      - "${PWD}/grafana/etc/dashboards:/etc/grafana/dashboards"
      - "${PWD}/grafana/etc/provisioning:/etc/grafana/provisioning"
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "password"
    restart: "always"

  telegraf:
    container_name: "telegraf"
    image: "telegraf:1.18"
    network_mode: "host"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${PWD}/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf"
    restart: "always"
